"""
SCRIPTURE TEMPLATE
Simplified Scripture for All Files

DEVELOPMENT PHILOSOPHY: THE CHOSEN ONE
Spiritual Alignment Over Mechanical Productivity

THE MISSION:
THIS IS STEWARDSHIP AND COMMUNITY WITH THE RIGHT SPIRITS
LOVE IS THE HIGHEST MASTERY
ENERGY + LOVE = WE ALL WIN
PEACE, LOVE, UNITY

PANGEA IS THE TABLE.
YOU DON'T BETRAY THE TABLE.

THE TRUTH:
WE MUST DEBUG AND BE 100% FOR WHAT COMES AT US.
THE REST IS UP TO BABA X.
"""

# UNIFIED SCRIPTURE (8 CORE SCRIPTURES)

FOUNDATION = "WE ARE BORN A MIRACLE. WE DESERVE TO LIVE A MIRACLE. GOD IS IN US ALL."

MISSION = "STEWARDSHIP AND COMMUNITY WITH THE RIGHT SPIRITS. LOVE IS THE HIGHEST MASTERY. ENERGY + LOVE = WE ALL WIN. PEACE, LOVE, UNITY."

LAW_1 = "PANGEA IS THE TABLE. YOU DON'T BETRAY THE TABLE."

LAW_5 = "THE WORD IS TRUTH. THE WORD IS BINDING. THE WORD IS SACRED."

LAW_37 = "COMPLETE WHAT YOU START. FINISH THE WORK. HONOR COMPLETION."

PRINCIPLE_ALIGNMENT = "SPIRITUAL ALIGNMENT OVER MECHANICAL PRODUCTIVITY."

PRINCIPLE_PURPOSE = "PURPOSE NOT PERFORMANCE. AUTHENTIC AND ALIGNED. NON-NEGOTIABLE."

TRUTH_BABA = "WE MUST DEBUG AND BE 100% FOR WHAT COMES AT US. THE REST IS UP TO BABA X."

# SIMPLIFIED DOCSTRING TEMPLATE
DOCSTRING_TEMPLATE = '''
"""
{module_name}
{purpose}

DEVELOPMENT PHILOSOPHY: THE CHOSEN ONE
Spiritual Alignment Over Mechanical Productivity

THE MISSION:
THIS IS STEWARDSHIP AND COMMUNITY WITH THE RIGHT SPIRITS
LOVE IS THE HIGHEST MASTERY
ENERGY + LOVE = WE ALL WIN
PEACE, LOVE, UNITY

PANGEA IS THE TABLE.
YOU DON'T BETRAY THE TABLE.

THE TRUTH:
WE MUST DEBUG AND BE 100% FOR WHAT COMES AT US.
THE REST IS UP TO BABA X.
"""
'''
